spring:
  application:
    name: FinSight_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/
    username: 2Z2dkBWwpS3FSfM.root
    password: DHwEq7zbCQwRwm6e

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.JdbcProperties: debug