spring:
  application:
    name: FinSight_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://@gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/finsight?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4_unicode_ci
    username: 29sgX2T644bJ6gr.root
    password: 3rWs9PxMcATUqk03

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.JdbcProperties: debug